### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by peterny** [jacobborella/s2i-grails#1]
Hej Jacob,
Jeg tror du mangler at dokumentere forudsætninger:
- docker
- s2i
- java

Mvh. Peter (fra KB).

**Comment by jacobborella** [comment]
Hej Peter.

Jeg har skrevet dem ind under referencer, men det er en god pointe at flytte det op i forudsætninger, så det gør jeg lige. Ellers er du jo altid velkommen til at forke, rette og lave et pull request til mig i bedste open source stil:-)

Håber i øvrigt du kan bruge eksemplet:-)

**Comment by peterny** [comment]
Perfekt, tak.
