### ISSUE TITLE
Stop container

### ISSUE THREAD

**Issue by peterny** [jacobborella/s2i-grails#2]
Hej igen Jacob,

Jeg kunne ikke stoppe
docker run -p 8080:8080 grails-app
med CTRL-C

Prøvede derfor:
[pnr-admin@pnr-test-02 s2i-grails]$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
cc5af2b4b290        grails-app          "container-entrypo..."   37 minutes ago      Up 37 minutes       0.0.0.0:8080->8080/tcp   thirsty_jennings
[pnr-admin@pnr-test-02 s2i-grails]$ docker stop grails-app
Error response from daemon: No such container: grails-app
[pnr-admin@pnr-test-02 s2i-grails]$ docker kill grails-app
Error response from daemon: Cannot kill container: grails-app: No such container: grails-app

Måtte reboot'e serveren for at få den stoppet.
Er det et problem med din app, eller et problem med min Docker installation?

Mvh. Peter

**Comment by jacobborella** [comment]
CTRL-C virker ikke, da du ikke er i den terminal, der har grails processen.

Brug docker stop <container id> (i dit tilfælde cc5af2b4b290 eller thirsty_jennings, begge dele vil virke). Du kan ikke bruge grails-app, da det er navnet på det image du kører og ikke et id på containeren.

Du kan i øvrigt bruge -d parameter til run kommandoen for at køre i baggrunden. Jeg brugte den anden kommando for nemt at kunne vise loggen, men -d vil normalt være at foretrække.

**Comment by peterny** [comment]
Tak, fint.
